{% set name = "napari-boids" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-boids-{{ version }}.tar.gz
  sha256: 5aa7d9d3cbfe8ddca52e26d7444c47489dd29a62acb7192963738a558fee451f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - napari
    - numpy
    - python >=3.8,<3.11
    - scipy

test:
  imports:
    - napari_boids
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/leoguignard/napari-boids
  summary: A plugin to look at boids
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - leoguignard
